pipeline {
    agent any

    // 定義 Jenkins 在啟動任务時，跳出對話框讓您填寫的參數
    parameters {
        string(name: 'VM_COUNT', defaultValue: '3', description: '想要建立幾台目標 VM (容器)？')
        string(name: 'START_PORT', defaultValue: '2222', description: 'SSH 預設起始 Port 號？')
    }



    stages {
        stage('Checkout Code') {
            steps {
                // 因為我們設定了 SCM，Jenkins 會幫我們自動自動取得原始碼進入它的暫存工作區！
                // 以下所有操作都可以直接使用 repo 的相對路徑。
                echo '程式碼已從 Git/SCM 取得完成！'
            }
        }

        stage('Terraform Init') {
            steps {
                // 現在有了 SCM 工作區，只要用相對路徑切換進去即可：
                dir('terraform-lab') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Apply (開機器)') {
            steps {
                dir('terraform-lab') {
                    // 使用 sh 執行指令，並帶入 -auto-approve 省略 yes 輸入
                    // 並將上方定義的 Parameters 塞到 -var 裡面！
                    sh """
                    terraform apply -auto-approve \
                        -var="container_count=${params.VM_COUNT}" \
                        -var="start_port=${params.START_PORT}"
                    """
                }
            }
        }
    }
}
